### ISSUE TITLE
nengo-spa feedback

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo-sphinx-theme#15]
From https://github.com/nengo/nengo-spa/pull/214:

* Still uses Arial which I find less legible than Lato given that many of the SPA documentation pages have quite a lot of text.
* This might be purely my preference: But the new theme uses Courier for code instead of Menlo. I find the latter to be a much nicer font.
* The heading font is too large for some of the longish page titles in the SPA documentation (e.g. [this one](https://www.nengo.ai/nengo-spa/examples/intro_coming_from_legacy_spa.html) gets broken across four lines, though maybe some of the titles should be shortened)
  * The underscore in nengo_spa on the linked example hangs too low/doesn't work well with the given line spacing.
* The code width does not fit an 80 character line (though the textwidth is fine and should not get too wide either).
* If the navigation on the left is cut-off it only scrolls once your close to the end of the page. In the old theme it would scroll immediately independent of the scroll position of the main body.
* API pages in the old theme are better structured. There you can see at a glance where a new element starts thanks to the blue background of the heading. The new theme doesn't have such highlights and the member elements of a class look the same. Furthermore, there are two awkward boxes (one around `nengo_spa.` and one around the documented element).
* The tables with “Further members” for the nengo_spa main module API documentation don't look great. the description column on the right is too narrow.
* It is not clear wether the “See also” box for the `ActionSelection` class belongs to that class or the `thalamus` member because the shape of the octagon makes it look indented (while it is not).
* There is an awkward line break in “return type” in the documentation of methods.

**Comment by drasmuss** [comment]
The theme has been overhauled since these issues, and nengo-spa now uses that new theme.
