### ISSUE TITLE
Dynamic sidebar TOC highlighting doesn't work properly

### ISSUE THREAD

**Issue by drasmuss** [nengo/nengo-sphinx-theme#19]
E.g., if you scroll through https://www.nengo.ai/nengo-dl/reference.html#developers you'll notice that the highlighting gets stuck on "Operator builders".

**Comment by bmorcos** [comment]
Came here to say the same thing.... Scrolling through [Nengo Bones config options](https://www.nengo.ai/nengo-bones/examples/configuration.html#), the TOC dot doesn't progress beyond `Codecov config`

**Comment by drasmuss** [comment]
We looked into this and it's an issue on the Sphinx/Scrollspy side, not something specific to `nengo-sphinx-theme`. So we'll just hope for an upstream fix 🤷‍♂
