### ISSUE TITLE
Doc search broken for some queries

### ISSUE THREAD

**Issue by arvoelke** [nengo/nengo-sphinx-theme#28]
Example: https://www.nengo.ai/nengo/search.html?q=Ensemble

JS Console:
![Screenshot from 2019-05-06 15-44-11](https://user-images.githubusercontent.com/5420057/57250583-d1eb6580-7015-11e9-853f-e048460eaa88.png)

Other examples with similar (or sometimes the same) errors:
 - Connection
 - PES
 - Learning
 - Uniform
 - tuning
 - gain
 - nengo

Examples that are fine (no error):
 - asd
 - q
 - dt

Similar symptoms for nengo-loihi. Have not checked any others users of `nengo-sphinx-theme`.

**Comment by arvoelke** [comment]
This issue appears to be present in all of the docs.

**Comment by hunse** [comment]
Likely the same problem as mli/new-docs#105

**Comment by hunse** [comment]
Possibly related to https://github.com/sphinx-doc/sphinx/issues/6387, which should be fixed by https://github.com/sphinx-doc/sphinx/pull/6394 for some themes.

**Comment by hunse** [comment]
I think this is fixable by applying the same idea from sphinx-doc/sphinx#6394 to our theme here. However, I haven't been able to test this yet because it only shows up when the docs are online (not locally).
