### ISSUE TITLE
Download button always goes to the Nengo core installation page

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo-sphinx-theme#3]
It probably should go to the instructions for the currently viewed subproject?

**Comment by tbekolay** [comment]
I think this is related to the discussion in #2 about the top navbar links always going to the same place. That was the original intention, so if we're changing it to have the top navbar do project-specific things I think we'll have to rethink things a bit (e.g., does each project need an "Overview"? If not, then why does that go to the main Nengo overview, yet Download goes to the specific download page?)

**Comment by drasmuss** [comment]
This has been changed in the new theme so that now there's no Download button, and instead it goes to a general Nengo getting started page.
