### ISSUE TITLE
Make top/sidebar sticky?

### ISSUE THREAD

**Issue by drasmuss** [nengo/nengo-sphinx-theme#4]
Right now the top and sidebars are statically positioned in the page, so if you scroll down they both disappear and the only way to navigate to a different page is to scroll back up to the top.  Personally I like having the navbars be floating/sticky, so that they're always present no matter where you are on the page.  I could also see an argument for only having one or the other be sticky though?

**Comment by tbekolay** [comment]
This is/was a feature in the original crate theme, and there's a config option (see `theme.conf`) for a fixed navbar, and possibly the fixed sidebar. Not sure when that broke / was deliberately removed / was accidentally removed.

**Comment by celiasmith** [comment]
Wasn't on purpose, and i think it's a good idea at least for the top bar.  Kinda either way for me on the sidebar, but might as well float it as the space is used anyway.

**Comment by drasmuss** [comment]
Fixed in #10
