### ISSUE TITLE
Pin Sphinx version

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo-sphinx-theme#40]
To avoid issues like #28, we should pin the Sphinx version and write a release checklist that includes upgrading the Sphinx version and trying a few common tasks to ensure the Sphinx update doesn't break anything.

**Comment by drasmuss** [comment]
Internal discussion result is that we won't do this because it's unlikely that we'd be able to catch all the subtle issues that might arise at release time, so we might as well just upgrade when we can and troubleshoot as we go.
