### ISSUE TITLE
All-caps headings

### ISSUE THREAD

**Issue by drasmuss** [nengo/nengo-sphinx-theme#5]
The crate theme uses all-caps for the top-level heading on each page.  I find this can be kind of difficult to parse when we have headings that use mixed capitalization.  For example, when I read "NENGODL" I can't help but see "NEN-GOD-L".  I'd argue that it doesn't work great for crate either (e.g. "CRATEDB" -> "CRATED-B" https://crate.io/docs/crate/reference/en/latest/).  I could just add a space to separate things (e.g. "NENGO DL"), but that is something we're going to have to think about and remember for all headings on all projects. My inclination would be to use normal capitalization in the headings, if no one has a strong preference for the all-caps.

**Comment by tbekolay** [comment]
I also am not a fan of the font used for headings, so I'd be keen to pick a different one.

**Comment by celiasmith** [comment]
i guess my only general comment (i completely agree with these observations) is that i was thinking this kind of thing would be discussed/come out in the meetings with designers.  that being said, have a list of issues like this will be idea to drive that discussion :)

**Comment by jgosmann** [comment]
I was considering opening an issue because of the headings to. Capitalizing module names (which happens in the Nengo SPA API documentation) is technically incorrect because Python is case-sensitive.
