### ISSUE TITLE
Docstring anchors are vertically misaligned

### ISSUE THREAD

**Issue by arvoelke** [nengo/nengo-sphinx-theme#50]
Spotted when linking to the docs on [this Nengo forum post](https://forum.nengo.ai/t/how-to-normalize-the-nengo-spa-state/1028/3).

To reproduce on Chrome Version 78.0.3904.108 (Official Build) (64-bit): 
 - Visit https://www.nengo.ai/nengo/frontend-api.html#nengo.Network
 - Observe that the position of the screen is not aligned with the position of the anchor

e.g., the `nengo.Network` anchor

looks like:
---
![Screenshot from 2019-12-11 19-16-38](https://user-images.githubusercontent.com/5420057/70679700-c49cf600-1c4a-11ea-96ca-f369e8aec283.png)
---

should be:
---
![Screenshot from 2019-12-11 19-17-14](https://user-images.githubusercontent.com/5420057/70679727-da122000-1c4a-11ea-9275-1a1ed0ffeaf5.png)
---

This appears to apply to any part of the documentation that is generated from a docstring. This does not appear to apply to anchors elsewhere (e.g., [this anchor is fine](https://www.nengo.ai/nengo/getting-started.html#installation)). This effect appears to be independent of screen width.

**Comment by drasmuss** [comment]
As pointed out in https://github.com/nengo/nengo.github.io/issues/92, this is probably because it isn't taking into account the height of the top navbar.

**Comment by tbekolay** [comment]
We take it into account for `h1` etc headers by introducing a psuedo-element before the header that is invisible, but pushes it down the screen. Hopefully we can do the same thing for these elements (just have to find the right CSS selector).
