### ISSUE TITLE
Include [source] links to GitHub for all nengo docs

### ISSUE THREAD

**Issue by arvoelke** [nengo/nengo-sphinx-theme#60]
(Feature request) 

I find it very useful when the docs link directly to GitHub. This allows you to easily do things like click on the function calls in the body, check the history of the file, navigate the directory, etc. For example: [nengolib.synapses.LegendreDelay](https://arvoelke.github.io/nengolib-docs/nengolib.synapses.LegendreDelay.html#nengolib.synapses.LegendreDelay) has a `[source]` link in the top-right corner that takes you directly to the function, tagged by the appropriate version. NumPy and SciPy do the same. I make use of this regularly (and find myself regularly wanting this feature for Nengo docs as well).

The way this is done in nengolib is through the `sphinx.ext.linkcode` plugin, with [a borrowed `linkcode_resolve` implementation](https://github.com/arvoelke/nengolib/blob/4f259e51410405f2f266b43b6338406db4b2b2ff/docs/conf.py#L123-L166).

**Comment by drasmuss** [comment]
Done in https://github.com/nengo/nengo-sphinx-theme/pull/66
