### ISSUE TITLE
Clean up and validate HTML

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo-sphinx-theme#7]
I noticed that at least in the sidebar is some invalid HTML:
```html
<ul class="bs-docs-sidenav bs-sidenav nav" role="complementary">
  <ul class="toctree nav nav-list">
    <ul class="current">
```
The `<ul>` tags are not allowed to be directly nested. There might be further instances of invalid HTML in the theme. [Reasons why it might be worth to care about this.](https://stackoverflow.com/questions/1337928/whats-the-point-of-valid-css-html)

**Comment by jgosmann** [comment]
(Also at least one of those lists has only one item ... not sure that three nested lists are actually needed.)

**Comment by drasmuss** [comment]
This is resolved in the new version of the theme.
